[build-system]
requires = ["setuptools", "cython", ]
build-backend = "setuptools.build_meta"

[project]
name = "xpra"
authors = [
    {name = "Antoine Martin", email = "antoine@xpra.org"},
]
description = "multi-platform screen and application forwarding system"
readme = "README.md"
requires-python = ">=3.10"
keywords = []
license = {text = "GPL2+"}
classifiers = [
    "Programming Language :: Python :: 3",
]
dependencies = [
    "gobject-introspection",
]


[tool.ruff]
line-length = 120

ignore = ["E741"]
